package GameModes;

public interface FinalVariables {
    int FIRST_LEVEL_OVERALL_RATING = 40;
    int SECOND_LEVEL_OVERALL_RATING = 60;
    int THIRD_LEVEL_OVERALL_RATING = 80;
    int MAX_FOOTBALL_PLAYERS_IN_TEAM_SIZE = 23;
    int MAX_LEVEL_UPGRADE = 3;

    Character EMPTY_STAR_FOR_FOOTBALL_PLAYERS = '\u2606';
    Character FULL_STAR_FOR_FOOTBALL_PLAYERS = '\u2605';
    Character CAPTAIN_SYMBOL_FOR_FOOTBALL_PLAYERS = '\u24B8';
    Character CHECK_MARK_POINTING_IF_FOOTBALL_PLAYER_HAS_CHEMISTRY_STYLE_FROM_THAT_SIDE = '\u2713';

    int FOOTBALL_PLAYER_CARD_MAXIMUM_ROW_SIZE = 13;

}
